### ISSUE TITLE
Example for building a model with a raster file

### ISSUE THREAD

**Issue by diegotxegp** [Deltares/hydromt_sfincs#108]
Hello everyone,

I am writing to ask for steps to build a model with a raster file (ASCII or TIFF). The pre-defined examples are confusing to extrapolate for my case. I will appreciate any help.

**Comment by DirkEilander** [comment]
Hi @diegotxegp , in the examples the model is build with raster data. For instance in step 3 of [this example](https://deltares.github.io/hydromt_sfincs/latest/_examples/build_from_script.html). You can replace "merit_hydro" with a reference to your dataset by providing its source name from your data catalog file or the path (only for a raster file that is directly recognized by hydromt such as a tif file). See also the "working with data" example. Hope this helps. Feel free to reopen an issue if you still have questions. Try to be as specific as possible.
