### ISSUE TITLE
Bugs setting up wind and pressure forcing

### ISSUE THREAD

**Issue by WOTrompDeltares** [Deltares/hydromt_sfincs#122]
setup_wind_forcing_from_grid():
Passing a xarray.Dataset to setup_wind_forcing_from_grid containing more than just the windspeeds will read in all the variables in the dataset to the config (see the sf.config.keys at the bottom). This gives (at least) issues with sf.plot_forcing(). An xarray.Dataset which only contains windspeeds works fine
![image](https://github.com/Deltares/hydromt_sfincs/assets/142423474/fe750fe1-6383-4b4f-a1f1-627a12723bd1)

setup_pressure_forcing_from_grid():
The rename method with the current syntax in setup_pressure_forcing_from_grid() only works for xarray.Dataarray, not xarray.Dataset. A work around is to select only the pressure data from the xarray.Dataset before calling the setup function (this returns a Dataarray instead of a Dataset)
![image](https://github.com/Deltares/hydromt_sfincs/assets/142423474/a42a2ca8-ece5-4e4f-a6a1-0d219420979a)

**Comment by DirkEilander** [comment]
Thanks for posting these issues!

Currently the DataAdapters we use to read / pre-process the data do not have the exact same functionality when parsing python objects (e.g., xarray Dataset/Array) compared to when reading data from file. We are working on this in the HydroMT core and I think this would be solved with https://github.com/Deltares/hydromt/pull/481 

You could either try installing that branch until the next hydromt core release or do the slicing & renaming before you pass the data to the methods (basically the work around you already describe).

**Comment by roeldegoede** [comment]
I expect this issue to be solved with the latest HydroMT and HydroMT-SFINCS releases.
