### ISSUE TITLE
setup_subgrid(..., write_dep_tif=True) just results in Geotiff of 0s

### ISSUE THREAD

**Issue by TPCollings** [Deltares/hydromt_sfincs#134]
I'm building a model of an area on the west coast of Florida, US. When setting up subgrid tables, the output .tif file just contains 0s. I believe the subgrid tables are set up correctly, as when I plot the zmin variable directly, it plots the topobathy as expected (see below).
 
![image](https://github.com/Deltares/hydromt_sfincs/assets/100429378/e9c7207b-fdda-43aa-bf79-000aa2f3339d)

The output of the .tif I see in Qgis is: 
![image](https://github.com/Deltares/hydromt_sfincs/assets/100429378/05d25e6a-aec1-44e5-bed9-9e911bc34c5a)

To create the subgrid tables I'm using the following code: 

![image](https://github.com/Deltares/hydromt_sfincs/assets/100429378/5b6930bb-7cdc-4704-bff2-da682cf8c0f9)

where the depth dataset is a custom pre-made blend of lidar, fabdem and gebco etc.

**Comment by roeldegoede** [comment]
Hi Tom, 

Nice that you are working with HydroMT-SFINCS! I expect that you have installed the latest release (v1.0.1), in which we unfortunately introduced this error ... We fixed it immediately afterwards, but that is not yet in a released version (https://github.com/Deltares/hydromt_sfincs/commit/73d8c2317ed9fc928b9e9ea894b607edc107be01).

Though the subgrid itself should be fine (and the data in the geotiff also), this error doesn't allow for visualization in QGIS. In case you need that, you could make a local clone of this repository and than install that version in your environment, e.g. using pip install <path_to_your_clone>.

Hope this clarified your question and sorry for the inconvenience.

Roel

**Comment by TPCollings** [comment]
Hi Roel,

Thanks for your response. I'll install directly from github to correct it.

I've been looking at the downscaling function in utils, is this geotif not required for use in that?

Cheers,

Tom

**Comment by roeldegoede** [comment]
Hi Tom,

It is indeed recommended to use this "merged" geotiff in the downscaling approach, although you could also use the raw elevation-input data for downscaling. If I remember correctly, the merged geotiff does contain data (though it doesn't show up in qgis), so using it from python would then still be possible. If that is not the case, I'm afraid you have to rerun it with the newer version ...

Sorry for the inconvenience,
Roel

**Comment by TPCollings** [comment]
Ah perfect, yeah the geotiff still works with the downscaling function. Thanks for your help!
