### ISSUE TITLE
Using pandas geodataframe for rivers in setup_river_inflow gives valueError

### ISSUE THREAD

**Issue by TBovenschen** [Deltares/hydromt_sfincs#135]
In the setup_river_inflow function according to the documentation you can add a pandas geodataframe as input for the 'rivers' argument. The dataFrame is however compared to a string in sfincs.py line 815. This gives the following error because it compares all cells of the dataframe to the string:
_ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()_

I think wrapping the rivers object in a str() function would solve the problem (and the option of giving a path string to the file also still works):
_elif str(rivers) == "rivers_outflow" and str(rivers) in self.geoms:_

I can add a pull request if you agree

**Comment by DirkEilander** [comment]
Good catch! 

I think it would be best to change to
`elif isinstance(rivers, str) and rivers == "rivers_outflw" and rivers in self.geoms:`

Would be great if you can make a PR for this!
