### ISSUE TITLE
utils.downscale_flodmap cannot handle path objects

### ISSUE THREAD

**Issue by dladrichem** [Deltares/hydromt_sfincs#150]
### HydroMT-SFINCS version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT-SFINCS.

### Reproducible Example

In utils.downscale_floodmap, floodmap_fn can be either a string or a path. This is used in the hydromt function raster.to_raster. To_raster strictly expects a string

### Current behaviour

If you input a path object, to_raster gives the error that you can't run endswith on a path object (which is correst, that is a method for strings)

### Desired behaviour

Either remove the Path as an optional input type for floodmap_fn, or convert the path to a string in the function itself (the second would be prefered since users don't have to change anything then)

**Comment by DirkEilander** [comment]
this is fixed in #151 right? If the issue still exist please reopen.
