### ISSUE TITLE
add support for restart file

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt_sfincs#17]
see https://sfincs.readthedocs.io/en/latest/input.html?highlight=restart#restart-file

**Comment by Leynse** [comment]
Users could already use this feature if they would specify the 'restartfile' keyword in the *.ini file under [setup_config]. 
Then is only a matter of describing in the docs.
Or are you planning to be able to read in the created ascii water level file?

**Comment by DirkEilander** [comment]
That is what I had in mind indeed. I think it should be easy to read/write these files. The model api has a `states` property and `read_states`/`write_states` methods designed for this purpose. This would enable users to easy interact (e.g. plot/edit) this file.
