### ISSUE TITLE
nlcd_mapping.csv file not found

### ISSUE THREAD

**Issue by Jiangchao3** [Deltares/hydromt_sfincs#172]
### HydroMT-SFINCS version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT-SFINCS.

### Reproducible Example

Hi Roel or other developers,

Happy new year! Thanks for updating the package to the latest version 1.0.3!

I am trying to using hydromt_sfincs to develop the inundation model, several issues occured   so want to consult with you:

I follow the example's step to generate the sfincs input files, previous step works very well, but when i try to set up the manning roughness, **when i use the esa_worldcover dataset, the following code works very well, i can plot the manning map.**

datasets_rgh = [{"lulc":"esa_worldcover"}] 
sf.setup_manning_roughness(
     datasets_rgh=datasets_rgh,
     manning_land=0.04,
     manning_sea=0.02,
     rgh_lev_land=0)  # the minimum elevation of the land)
sf.plot_basemap(variable="manning", plot_bounds=False, bmap="sat", figsize=(12,7), zoomlevel=12)

### Current behaviour

**But when i use the nlcd dataset with `datasets_rgh = [{"lulc":"nlcd"}]`, it says:**

File ~/miniconda3/envs/hydromt-sfincs/lib/python3.10/site-packages/hydromt/data_adapter/data_adapter.py:398 in _resolve_paths
    raise FileNotFoundError(f"No such file found: {path}{postfix}")
**FileNotFoundError:** No such file found: /home/qiujch24/miniconda3/envs/hydromt-sfincs/lib/python3.10/site-packages/hydromt_sfincs/data/lulc/nlcd_mapping.csv

### Desired behaviour

**I found there are two mapping.csv file in the DATA/lulc folder: NLCD_HSG.csv, and NLCD_SFBD_mapping.csv.**

**I am not sure if this error is caused by the wrong csv file name?**

Looking forward to your reply!

### Additional context

Many thanks,

Jiangchao

**Comment by Jiangchao3** [comment]
Besides,

after i update to the latest hydromt_sfincs v1.0.3, `gdf_riv = sf.geoms["rivers_inflow"].copy()` didn't work, it says:

Traceback (most recent call last):

  Cell In[34], line 6
    gdf_riv = sf.geoms['rivers_inflow'].copy()

**KeyError: 'rivers_inflow'**

but it did work before i update the package!

**Comment by DirkEilander** [comment]
Thanks for your question. We should document this better!

In case you are not using esa_worldcover, vito, corine or globcover you need to specify your own reclassification table, see below how such table should look like (with lulc classes in the first column and a `N` column with manning values). You can prepare this file as a csv file and add it to the data catalog. Both are called with the proper datacatalog name. We recommend using more detailed local datasources if those are available. 

**example reclass table to map landuse to roughness values (N)**
| class | description               | N     |
|-------|---------------------------|-------|
| 10    | Tree cover                | 0.12  |
| 20    | Shrubland                 | 0.05  |
| 30    | Grasland                  | 0.034 |
| ..    | ........                  | ..... |
| 0     | No data                   | -999  |

**example datasets_rgh with landuse and reclass table**
```python
datasets_rgh = [
    {
        'lulc': 'esa_worldcover',   # landuse/landcover dataset
        'reclass_table': 'esa_worldcover_mapping' # reclassification table
    }
]
```

**example data catalog yml file entry for the landuse and reclass tables**
```yml
esa_worldcover:
  data_type: RasterDataset
  path: esa_worldcover.tif
  driver: raster
  filesystem: local
  meta:
    category: landuse
    source_license: CC BY 4.0
    source_url: https://doi.org/10.5281/zenodo.5571936
    source_version: v100
  crs: 4326
esa_worldcover_mapping:
  data_type: DataFrame
  path: esa_worldcover_mapping.csv
  driver: csv
  meta:
    category: landuse
    notes: Manning Roughness values for each ESA World Cover class
```

**Comment by DirkEilander** [comment]
TODO:

- [ ] add reclass_table option to user guide example

**Comment by Jiangchao3** [comment]
Thanks very much @DirkEilander, very clear!

**Comment by Jiangchao3** [comment]
Hi @DirkEilander, I follow your suggestion and provide the mapping csv file in the data catalog, something shows different between using and not using the reclass table, it is a bit odd:

1. this figure shows the manning map using `datasets_rgh = [{"lulc":"esa_worldcover"}]`

![manning_esa](https://github.com/Deltares/hydromt_sfincs/assets/66854878/1c671e95-f8f3-451b-afbc-4d3e1f2a2455)

2. this figure shows the manning map using `datasets_rgh = [{'lulc': 'esa_worldcover', 'reclass_table': 'esa_worldcover_mapping' }]`

![manning_esa_table](https://github.com/Deltares/hydromt_sfincs/assets/66854878/9ae38a0c-c574-4c66-abce-a8ec5c524961)

3. this figure shows the manning map using `datasets_rgh = [{'lulc': 'nlcd', 'reclass_table': 'nlcd_sfbd_mapping' }]`

![manning_nlcd_table](https://github.com/Deltares/hydromt_sfincs/assets/66854878/0f8a05b6-2b5e-4a1d-b898-7d59c9976faf)

**the nlcd_sfbd_mapping.csv and esa_worldcover_mapping.csv file is download from your /data/lulc/ folder in hydromt_sfincs**

**This area is the Broward country in southeast Florida, i guess the first manning mapping is correct, since the east coast of broward is developed area, the manning value should be larger than 0.1, but the two figure using reclass tables only show the largest value of 0.04 for the whole domain.**

<img width="799" alt="image" src="https://github.com/Deltares/hydromt_sfincs/assets/66854878/53ec6dd8-52b3-40a8-8255-c6fb22aa76ae">

**Curious about what happens about these different methods!**

Best,
Jiangchao

**Comment by roeldegoede** [comment]
Hi @Jiangchao3, I have my doubts whether the specified reclass tables can be found. It more seems to use constant values of 0.04 for land, and 0.02 for water, what is typical when no roughness values can be determined.

By not providing the reclasss_table, it automatically searches for "hydromt_sfincs/data/lulc/<data_name>_mapping.csv", which therefore essentially results in the esa_worldcover_mapping.csv. This results in the logical roughness map of option 1. However, with your 2nd option, you specify a reclass_table "esa_worldcover_mapping", which is just a string. To be able to use these strings, you should make sure that "esa_worldcover_mapping" is present in your SfincsModel.data_catalog and pointing to the correct location of the corresponding file.

Dirk provided an example of how you could add these files to your data_catalog. Note, instead of using the data_catalog (which is very elegant and enables easier use in different projects), you could also use an absolute path for the reclass table, e.g.: reclass_table: "c:/hydromt_sfincs/data/lulc/nlcd_mapping.csv".

Hopefully this solves the problems of options 2 and 3.

Cheers,
Roel

**Comment by Jiangchao3** [comment]
Thanks very much for the suggestion @roeldegoede, I am not sure why the data_catalog method did not work, but i tried your absolute path method, it works for the nlcd dataset.

![manning_nlcd_table](https://github.com/Deltares/hydromt_sfincs/assets/66854878/dd10d4b3-2643-4e28-9934-ce37869b68a6)

Best,
Jiangchao

**Comment by DirkEilander** [comment]
I had made a mistake in the data catalog. We need to tell the driver (pandas.read_csv) to set the first column as index (note the `driver_kwargs` below)

```yml
esa_worldcover_mapping:
  data_type: DataFrame
  path: esa_worldcover_mapping.csv
  driver: csv
  driver_kwargs:
    index_col: 0
```

**Comment by Jiangchao3** [comment]
@DirkEilander Thanks and good to know this!
