### ISSUE TITLE
add support for spatially constant precipitation

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt_sfincs#18]
see https://sfincs.readthedocs.io/en/latest/input_forcing.html#spatially-uniform

**precipfile = sfincs.prcp**

```
<time 1> <prcp0>
<time 2> <prcp1>

e.g.
0       0
3600    15
7200    10
```

**Comment by Leynse** [comment]
Format is in principlethe same as a *.bzs/.*dis file, though with only 1 column for values.
Probably can re-use the existing timeseries methods of e.g. [setup_q_forcing]
