### ISSUE TITLE
Setup grid from region with bounding box in different CRS

### ISSUE THREAD

**Issue by saschahofmann** [Deltares/hydromt_sfincs#182]
### HydroMT-SFINCS version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT-SFINCS.

### Reproducible Example

I am trying to setup the grid with a bounding box that is already in a different CRS e.g. like this

```python
bbox = [406565.1340,4567290.4902,436760.4489,4585912.0943]

sf.setup_grid_from_region(
    dict(bbox=bbox),
    res=200,
    crs=32631,
)
```
Which I think leads to the self.geoms being full of `inf`

### Current behaviour

It fails with `ValueError: cannot convert float NaN to integer` in *hydromt_sfincs/sfincs.py:303*

### Desired behaviour

I think in L408 of model_api.py where the bounding box is created via GeoPandas it could probably use a dynamic CRS?

**Comment by roeldegoede** [comment]
Thanks for bringing this up, I see the confusion! 

- For a bbox, we now always expect lat/lon (wgs84). Then you could still specify a CRS that you would like your model to be in (like you did), but the bbox itself should be in lat/lon.
- You could also use projected inputs, but that would be as a "geom" input, which expects a geodataframe basically that can be in any coordinate reference system.

**Comment by saschahofmann** [comment]
Alright, to be honest for some reason I thought they should be supplied in the projects CRS and it took me a while to get them, was much easier to just use the lat lon from WG84 so that makes sense. Then maybe the only thing to do is mention it in the docs? I can make a PR if you want otherwise I'll just close this.
Thanks for the quick help.

**Comment by roeldegoede** [comment]
Always happy to have contributions that make our docs more clear, so it would be great if you could make a PR.
