### ISSUE TITLE
[Error] x dimension not found. Use 'set_spatial_dims' functions with correct x_dim argument provided.

### ISSUE THREAD

**Issue by babuinorei** [Deltares/hydromt_sfincs#190]
### HydroMT-SFINCS version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT-SFINCS.

### Reproducible Example

////////////////////////////////////////////////////traceback below:

Cell In[26], line 1
----> 1 sf.setup_waterlevel_forcing(geodataset='waterlevel_test',buffer=1000)

File ~\miniconda3\envs\hydromt-sfincs-course\lib\site-packages\hydromt_sfincs\sfincs.py:1829, in SfincsModel.setup_waterlevel_forcing(self, geodataset, timeseries, locations, offset, buffer, merge)
1826 # read waterlevel data from geodataset or geodataframe
1827 if geodataset is not None:
1828 # read and clip data in time & space
-> 1829 da = self.data_catalog.get_geodataset(
1830 geodataset,
1831 geom=region,
1832 buffer=buffer,
1833 variables=["waterlevel"],
1834 time_tuple=(tstart, tstop),
1835 crs=self.crs,
1836 )
1837 df_ts = da.transpose(..., da.vector.index_dim).to_pandas()
1838 gdf_locs = da.vector.to_gdf()

File ~\miniconda3\envs\hydromt-sfincs-course\lib\site-packages\hydromt\data_catalog.py:876, in DataCatalog.get_geodataset(self, data_like, bbox, geom, buffer, variables, time_tuple, single_var_as_array, **kwargs)
871 self._used_data.append(name)
872 self.logger.info(
873 f"DataCatalog: Getting {name} GeoDataset {source.driver} data"
874 f" from {source.path}"
875 )
--> 876 obj = source.get_data(
877 bbox=bbox,
878 geom=geom,
879 buffer=buffer,
880 variables=variables,
881 time_tuple=time_tuple,
882 single_var_as_array=single_var_as_array,
883 logger=self.logger,
884 )
885 return obj

File ~\miniconda3\envs\hydromt-sfincs-course\lib\site-packages\hydromt\data_adapter\rasterdataset.py:353, in RasterDatasetAdapter.get_data(self, bbox, geom, buffer, zoom_level, align, variables, time_tuple, single_var_as_array, cache_root, logger)
350 ds_out = ds_out[variables]
352 # transpose dims to get y and x dim last
--> 353 x_dim = ds_out.raster.x_dim
354 y_dim = ds_out.raster.y_dim
355 ds_out = ds_out.transpose(..., y_dim, x_dim)

File ~\miniconda3\envs\hydromt-sfincs-course\lib\site-packages\hydromt\raster.py:294, in XRasterBase.x_dim(self)
292 """Return the x dimension name."""
293 if self.get_attrs("x_dim") not in self._obj.dims:
--> 294 self.set_spatial_dims()
295 return self.attrs["x_dim"]

File ~\miniconda3\envs\hydromt-sfincs-course\lib\site-packages\hydromt\raster.py:362, in XRasterBase.set_spatial_dims(self, x_dim, y_dim)
360 self.set_attrs(x_dim=x_dim)
361 else:
--> 362 raise ValueError(
363 "x dimension not found. Use 'set_spatial_dims'"
364 + " functions with correct x_dim argument provided."
365 )
367 if y_dim is None:
368 for dim in YDIMS:

ValueError: x dimension not found. Use 'set_spatial_dims' functions with correct x_dim argument provided.

### Current behaviour

Hello everyone, I am trying to derive data for my model in a netCDF format and I end up having the same Error regarding to the dimensions everytime.

I reproduced the netCDF build the same as one that worked (provided by Deltares).

The data is for the waterlevel forcing.

### Desired behaviour

Read properly the netCDF file. I can leave the structure of mine if needed.

If you guys have anything that could help me it would be nice. 

thank you and regards!

**Comment by roeldegoede** [comment]
@babuinorei could you share your file that you try to use?

Something that we often apply for the geodatasets is renaming of the coordinates. For typical GTSM (Delft3D-FM output), we use the following data_catalog entry:

```
gtsm_output:
  path: <yourpath>/output/output_his.nc
  data_type: GeoDataset
  driver: netcdf
  crs: 4326
  kwargs:
    chunks:
      stations: 10
      time: -1
  rename:
    station_x_coordinate: lon
    station_y_coordinate: lat
    stations: index
```

**Comment by babuinorei** [comment]
Hello @roeldegoede , thank you for the fast response.

Sure I can try this, meanwhile I am sharing the file:
[output1990_waterlvl.zip](https://github.com/Deltares/hydromt_sfincs/files/14654219/output1990_waterlvl.zip)

**Comment by roeldegoede** [comment]
Had a quick look at your data and that looks fine! Had to figure out what kind of model you were making and where it is located (so please make it more easily reproducible next time), but all in all it seems to work on my side.

Extra data catalog I used:

```
wlev_test:
  path: output1990_waterlvl\output1990.nc
  data_type: GeoDataset
  driver: netcdf
  crs: 4326
  kwargs:
    chunks:
      stations: 10
      time: -1

```

and then a random model:

```
mod = SfincsModel(
    root = "Downloads//output1990_waterlvl",
    mode = "w+",
    data_libs = ["deltares_data",  # used for elevations
                "output1990_waterlvl//data_catalog.yml"],
)

mod.setup_grid_from_region(
    {'bbox': [3.59749551-0.5, 51.44230361-1, 3.59749551+2, 51.44230361+2]},
    res = 0.05,
    crs = 4326,
)

mod.setup_dep(
    datasets_dep = [{"elevtn": "merit_hydro", "zmin": 0.01},{"elevtn": "gebco"}]
)

mod.setup_mask_active(
    zmin = -25,
)

mod.setup_mask_bounds(btype="waterlevel", zmax=0)

# important for clipping in time
mod.setup_config(
    **{
        "tref": "19200225 000000",
        "tstart": "19200225 000000",
        "tstop": "19200301 000000",
    }
)


mod.setup_waterlevel_forcing(
    "wlev_test",
    buffer=100000, #important for clipping in space
)

```


Couple of attention points:
- The geodataset is clipped in time and space, so make sure the time-frame overlap with the timeframe of the data
- For the clipping in space, a buffer is applied around your "waterlevel" boundary. You could add a very large buffer to make sure it falls within the spatail domain.

**Comment by babuinorei** [comment]
Roel, thank you very much, it worked!

I changed the number of stations, and got another dataset with more stations.

I think the issue was related to the domains of my waterlevel boundary.

anyway thanks!
