### ISSUE TITLE
write forcing precision

### ISSUE THREAD

**Issue by guzrf** [Deltares/hydromt_sfincs#197]
### Kind of request

Changing existing functionality

### Enhancement Description

Hi, I just wanted to make a suggestion for a modification to the write_forcing() function in sfincs.py. When saving the hydrograph data in the .bzs file I miss the possibility to specify the precision with which to save the data.

Although it is true that the write_timeseries() function of utils.py can be called separately to specify the precision, it would be nice if the write_forcing() function could handle this option.

### Use case

For example, it could be an attribute of the class, so that when calling the SfincsModel.write() function, if the precision for the .bzs file has been previously specified, the file would be saved with the desired precision without the need to add arguments to the functions.

**Comment by roeldegoede** [comment]
Good suggestion, I guess we can easily add a fmt argument to SfincsModel.write_forcing and parse that fmt argument to the utils.write_timeseries() function. 

Am I understanding correctly that you also suggest that we "derive" the format of each forcing condition when reading in the model, to make sure it remains in the same format when writing it again?

**Comment by roeldegoede** [comment]
We finally made some changes that partially adress this issue in #210. You are now enabled to set the precision of the forcing when writing to make sure you don't lose information. However, it does not yet derive the precisions of the different forcings and store it as an attribute of the SfincsModel.

Hopefully this first solution is already helpfull for you. Storing it as an attribute has a bit of a lower priority from our side, but you are more than welcome to make a suggestion in the code for this.
