### ISSUE TITLE
How to make the mask geodataframe using openstreet waterbodies

### ISSUE THREAD

**Issue by Jiangchao3** [Deltares/hydromt_sfincs#203]
### Kind of request

None

### Enhancement Description

hi @roeldegoede or @DirkEilander, I am trying to mask flood area using the openstreet waterbodies [https://hydro.iis.u-tokyo.ac.jp/~yamadai/OSM_water/](url).

Since the utils.downscale_floodmap need a geodataframe object for the input gdf_mask, 
i have a simple question abou how to generate it. Please see my code in the screensnaps:

**First I use the following code to let all the land area are true**:

![image](https://github.com/Deltares/hydromt_sfincs/assets/66854878/9450904e-d27f-4273-936c-9aa3723e9661)

**Second, I need to convert the dataarray into a geodataframe**:

![image](https://github.com/Deltares/hydromt_sfincs/assets/66854878/1cb79e9a-1fec-4520-9319-53d1b45fab9b)

**But the geometry should be MULTIPOLYGON rather than point, I know using x,y point to generate the geodateframe is wrong, but I don't know how to convert it to let each pixle be a polygon.** Since each pixle is not just a point at (x,y), it should have a grid width.

**Do you have some suggestion to generate a right geodataframe mask in hydromt or hydromt_sfincs?** 

Many thanks.

Jiangchao

**Comment by wangxla** [comment]
You can use ArcGIS tools to help you with your task. Make sure you do not check the "Simplify polygons" box.
![image](https://github.com/Deltares/hydromt_sfincs/assets/62167951/0ba96413-ab78-4012-8058-65204358f7a7)

**Comment by Jiangchao3** [comment]
**I use the following code to convert tif/raster to geodatafram first:**

![image](https://github.com/Deltares/hydromt_sfincs/assets/66854878/af162fba-64bf-4b6d-995d-da55bd2d8a3b)

**then read into using read_geodataframe:**

![image](https://github.com/Deltares/hydromt_sfincs/assets/66854878/5379952b-fae2-4366-812e-9dc1bfaf2837)

**then downscale the flood map using the osm_mask:**

![image](https://github.com/Deltares/hydromt_sfincs/assets/66854878/9a7eab26-ec1e-4ef9-b766-66729b07d516)

**Comment by Jiangchao3** [comment]
**I use the following code to convert tif/raster to geodatafram first:**

![image](https://github.com/Deltares/hydromt_sfincs/assets/66854878/af162fba-64bf-4b6d-995d-da55bd2d8a3b)

**then read into using read_geodataframe:**

![image](https://github.com/Deltares/hydromt_sfincs/assets/66854878/5379952b-fae2-4366-812e-9dc1bfaf2837)

**then downscale the flood map using the osm_mask:**

![image](https://github.com/Deltares/hydromt_sfincs/assets/66854878/9a7eab26-ec1e-4ef9-b766-66729b07d516)
