### ISSUE TITLE
default vertical datum and method to merge topo/bathy data

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt_sfincs#22]
Currently the default vertical datum is set the datum of the DEM (typically EGM96)  for both coastal and riverine models and the bathymetry data (in setup_basemaps) and waterlevel data (in setup_h_forcing) can be corrected to this datum using a DTM file. Wouldn't it be better to (make it possible to) correct the DEM to MSL in case of coastal models after which we don't have to correct bathymetry and water level data? This could be achieved by a more simple `setup_basemaps` to set the model domain and create a dep file based on a single DEM source and a possible correction DTM map. A new `setup_merge_topobathy` method would add a second (or third, ..) source with possible correction; merge method; resampling method; and the option to interpolate within a buffer between the new and original sources. This would also allow to merge a third (e.g. local LIDAR DEM) in the dep file by reusing this method. The water boundary cells (mask=2) are set in a separate function.

**Current basemaps options:**

```
[setup_basemaps]
basemaps_fn = merit_hydro      
landmask_fn = osm_landareas    
bathymetry_fn = gebco        
mdt_fn = dtu10mdt_egm96      
merge_buffer = 0           
interpolationmask_fn = None                  
dep_contour = -1
```

**Proposed basemap options and new methods:**
```
[setup_basemaps]
basemaps_fn = merit_hydro      
datum_correction_fn = egm96_to_msl

[setup_merge_topobathy]
topobathy_fn = gebco
datum_correction_fn= None
merge_method=geometry          # {'first', 'last', 'min', 'max', 'geometry'}
merge_buffer=0                 # buffer (cells) between elevation and bathymetry data filled with 'linear' interpolation
geometry_fn= osm_waterareas    # if merge_method == 'geometry', polygon geometry where to use topobathy source
resampling_method=bilinear

[setup_h_bound]
mask_fn         = osm_landareas   # polygon mask of active cells; cells that intersect with its boundary get a mask=2 value
dep_contour    = -1               # alternativly: set mask=2  based on a depth contour
```

@Leynse  / @panosatha : like to hear your thoughts on this.

**Comment by DirkEilander** [comment]
After discussion with @panosatha it seems best to not reproject the MDT. This is possible with a single topo/bathy data source which can, if necessary, be referenced to the same geoid as the MDT using the difference between geoids (grid from Panos). In this case the MDT is only used to change the vertical datum of the water levels.  However, when we want to merge multiple topo/bathy data sources of which one is referenced to MSL we have to reproject the MDT to correct one of the topo/bath sources. 

@panosatha: Am I missing something or do you agree with the latter?

**Comment by panosatha** [comment]
@DirkEilander you mean that the MDT will be used to reproject the topo/bathy source which is referenced to a geoid, to MSL? It seems like a valid thought. But remember that the MDT is normally defined only at sea, but I think the DTU MDT is extrapolated inland, so the correction could be performed.
