### ISSUE TITLE
clarify documentation for netcdf with different dimension names than index_dim

### ISSUE THREAD

**Issue by couasnonanais** [Deltares/hydromt_sfincs#26]
For the SfincsModel.setup_h_forcing() and SfincsModel.setup_q_forcing(), the provided netcdf files should have the dimension name renamed to index_dim. This can be solved from 1- the .yml file or 2- by adding as a variable in the netcdf 'spatial_ref' with as attributes "index_dim" mentioning the appropriate index dimensions. Upgrading the documentation to show which index_dim are currently being supported and what to do if not in the list would be useful.

**Comment by DirkEilander** [comment]
Thanks for this suggestion @couasnonanais. The index_dim of a _geodataset_ netcdf does not have to be called as such. hydroMT should be able to figure out the index dim itself if there a x- and y-coordinates with this dimension. In the example below the index_dim is called stations and is recognized as it is the dimension of the x (lon) and y  (lat) coordinates. Recognized x and y dimension can be found [here](https://deltares.github.io/hydromt/latest/user_guide/data.html#supported-data-types-and-associated-drivers). The time dimension should be called time. 

```
Dimensions:      (stations: N, time: NT)
Coordinates:
  * time         (time)
  * stations     (stations)
    lon          (stations)
    lat          (stations)
Data variables:
    waterlevel   (time, stations)
```
For more information checkout the updated data section in the hydromt core docs: https://deltares.github.io/hydromt/latest/user_guide/data.html#netcdf-point-timeseries-dataset

Let me know if this solves your issue.
