### ISSUE TITLE
Clarify documentation/provide an example when using locations and timeseries from 2 different csv files for SfincsModel.setup_h_forcing()

### ISSUE THREAD

**Issue by couasnonanais** [Deltares/hydromt_sfincs#27]
I couldn't manage to have the code to exit successfully when wanting to provide a GeoDataset from two csv files (one for the locations of the station and one for the time series) for the function SfincsModel.setup_h_forcing(). It would be useful to discuss this option and provide an example. 

For some reason, I cannot manage to attach the csv files here, I will email them.

**Comment by DirkEilander** [comment]
This has been solved in the hydromt_sfincs v0.2.0 (but now works slightly different). An example is given in the data_catalog.yml file which is used in the setup_h_forcing component of the build_coastal_model example, see https://github.com/Deltares/hydromt_sfincs/tree/main/examples. I'll close this for now, but please feel free to reopen if it has not been fixed.
