### ISSUE TITLE
Generate boundary points along msk=2 boundary at interface with overlapping grid of offshore model

### ISSUE THREAD

**Issue by Leynse** [Deltares/hydromt_sfincs#52]
Approximate steps:
- Load in grid/mask of offshore model
- Find overlap with nested SFINCS model msk=2 cells
- Put some filter on how close together these points may be
- Write away points as sfincs.bnd file

**Comment by roeldegoede** [comment]
Added in SfincsModel.setup_waterlevel_bnd_from_mask
