### ISSUE TITLE
add offset_fn to setup_topography to be able to build a model referenced to MSL

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt_sfincs#58]
this suggestion was mentioned by @panosatha in relation to SFINCS models for (small) islands and specifically useful when comparing models based on DEMs with different reference levels.

**Comment by roeldegoede** [comment]
While setting up your topobathy (SfincsModel.setup_dep), every elevation dataset can be given an offset (constant value) or offset field.
