### ISSUE TITLE
release versie 1.0.0

### ISSUE THREAD

**Issue by roeldegoede** [Deltares/hydromt_sfincs#78]

**Comment by roeldegoede** [comment]
Hi Lauren, I haven't seen this error with the new version of HydroMT-SFINCS yet in combination with the d'Alpe d'Huez release, but I have seen it in earlier versions ...

So first thing I would check are the versions of HydroMT-SFINCS, which I assume is correct since you created a subgrid file, but also the SFINCS executable .. The released version can be found here: https://download.deltares.nl/en/download/sfincs/

HydroMT-SFINCS uses the epsg (in sfincs.inp) to read in the model. If not provided in the sfincs.inp, you can specify it while reading the model with SfincsModel.read(epsg=32618)

And the last thing that comes to mind to check the HydroMT-version, are you able to run the example sfincs_results_hmax.ipynb?

**Comment by lgrimley** [comment]
Hi Roel -- Specifying the epsg code when reading in the model seems to work. Thanks!!
