### ISSUE TITLE
Support Alpe d'Huez release

### ISSUE THREAD

**Issue by roeldegoede** [Deltares/hydromt_sfincs#89]
In the Alpe d'Huez release, the x,y coords are in a different order then in the latest version of SFINCS. Possible ways of solving:
- Distribute the newer version of SFINCS
- Support both versions with read_sfincs_map_results

Additionally, read_sfincs_his_results raises an error is the epsg code is mis-understood. I propse to fix this in a similar way as issue #66.

**Comment by DirkEilander** [comment]
I think it would be good to support both if it's not too complicated. Can you add a print of the coordinates after reading the outputs with xarray for both versions to the issue in order to understand it better? The CRS fix sounds good.

**Comment by roeldegoede** [comment]
Reading in the sfincs_map.nc of the alpe d'huez release:
![image](https://user-images.githubusercontent.com/83765910/235429863-03035bd3-6a04-49a2-8ee2-a3e4b0204b92.png)

Reading in the tagged version:
![image](https://user-images.githubusercontent.com/83765910/235430741-7674a67d-55ae-4644-9732-ac0c18cf9a19.png)
