### ISSUE TITLE
ENH: add setup_cross_sections

### ISSUE THREAD

**Issue by roeldegoede** [Deltares/hydromt_sfincs#96]
To monitor the discharge in rivers, a crsfile can be defined in the following format:

crsfile              = sfincs.crs

crs_01
2 2
453691 5410629
453307 5410240

crs_02
2 2
453691 5410629
453307 5410240

**Comment by lgrimley** [comment]
I just tested this out... works great! One thing to add is clipping the cross-section geometry shapefile to the model domain in the setup function. Currently it writes all the input cross-sections to the model -- even ones outside the model area.

**Comment by roeldegoede** [comment]
Hi Lauren, nice to hear that it (almost) works for you! 

So I just checked, and for me, cross-sections outside of the model region are clipped.. Something that we support since last release is that you can both provide in-memory datasets and filenames/dataset names from the data_catalog. We found out that the clipping doesn't work for the in-memory datasets (see also https://github.com/Deltares/hydromt/issues/335). 

Can this be an explanation why it didn't work for you?

**Comment by lgrimley** [comment]
Ah, yes. That would be the reason it didn't clip. Thanks!
